---
tower_inventories:
  - name: Workshop Inventory
    organization: Default

  - name: CentOS7 Development
    organization: Default
    variables:
      ansible_user: centos
      instances:
        tags:
          ContentView: CentOS7
          Environment: Dev
          guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"

  - name: CentOS7 Production
    organization: Default
    variables:
      ansible_user: centos
      instances:
        tags:
          ContentView: CentOS7
          Environment: Prod
          guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"

  - name: RHEL7 Development
    organization: Default
    variables:
      instances:
        tags:
          ContentView: RHEL7
          Environment: Dev
          guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"

  - name: RHEL7 Production
    organization: Default
    variables:
      instances:
        tags:
          ContentView: RHEL7
          Environment: Prod
          guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"

  - name: ALL Development
    organization: Default

  - name: EXAMPLE dynamic project inventory
    organization: Default

tower_inventory_sources:
  - name: satellite_source
    inventory: Workshop Inventory
    credential: Inventory Credential
    source: satellite6
    update_on_launch: false
    overwrite: true
    source_vars:
      keyed_groups:
        - prefix: env
          key: foreman_content_facet_attributes.lifecycle_environment_name
        - prefix: cv
          key: foreman_content_facet_attributes.content_view_name
        - prefix: os
          key: foreman_operatingsystem_name

  - name: EC2 Dynamic Source - CentOS7 Development
    inventory: CentOS7 Development
    source: ec2
    source_vars:
      regions:
        - "{{ workshop_ec2_region }}"
      filters:
        tag:ContentView: CentOS7
        tag:Environment: Dev
        tag:Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
        tag:guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
      hostnames:
        - tag:NodeName
      keyed_groups:
        - prefix: cv
          key: tags['ContentView']
        - prefix: env
          key: tags['ContentView'] ~ '_' ~ tags['Environment']
        - prefix: os
          key: tags['foreman_operatingsystem_name']
        - prefix: AnsibleGroup
          key: tags['AnsibleGroup']
      compose:
        # set the ansible_host variable to connect with the private IP address without changing the hostname
        ansible_host: private_ip_address
        ansible_user: "'centos'"
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0

  - name: EC2 Dynamic Source - CentOS7 Development - ALL
    inventory: ALL Development
    source: ec2
    source_vars:
      regions:
        - "{{ workshop_ec2_region }}"
      filters:
        tag:ContentView: CentOS7
        tag:Environment: Dev
        tag:Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
        tag:guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
      hostnames:
        - tag:NodeName
      keyed_groups:
        - prefix: cv
          key: tags['ContentView']
        - prefix: env
          key: tags['ContentView'] ~ '_' ~ tags['Environment']
        - prefix: os
          key: tags['foreman_operatingsystem_name']
        - prefix: AnsibleGroup
          key: tags['AnsibleGroup']
      compose:
        # set the ansible_host variable to connect with the private IP address without changing the hostname
        ansible_host: private_ip_address
        ansible_user: "'centos'"
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0

  - name: EC2 Dynamic Source - CentOS7 Production
    inventory: CentOS7 Production
    source: ec2
    source_vars:
      regions:
        - "{{ workshop_ec2_region }}"
      filters:
        tag:ContentView: CentOS7
        tag:Environment: Prod
        tag:Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
        tag:guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
      hostnames:
        - tag:NodeName
        - tag:Name
        - private-dns-name
      keyed_groups:
        - prefix: cv
          key: tags['ContentView']
        - prefix: env
          key: tags['ContentView'] ~ '_' ~ tags['Environment']
        - prefix: os
          key: tags['foreman_operatingsystem_name']
        - prefix: AnsibleGroup
          key: tags['AnsibleGroup']
      compose:
        # set the ansible_host variable to connect with the private IP address without changing the hostname
        ansible_host: private_ip_address
        ansible_user: "'centos'"
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0

  - name: EC2 Dynamic Source - RHEL7 Development
    inventory: RHEL7 Development
    source: ec2
    source_vars:
      regions:
        - "{{ workshop_ec2_region }}"
      filters:
        tag:ContentView: RHEL7
        tag:Environment: Dev
        tag:Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
        tag:guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
      hostnames:
        - tag:NodeName
      keyed_groups:
        - prefix: cv
          key: tags['ContentView']
        - prefix: env
          key: tags['ContentView'] ~ '_' ~ tags['Environment']
        - prefix: os
          key: tags['foreman_operatingsystem_name']
        - prefix: AnsibleGroup
          key: tags['AnsibleGroup']
      compose:
        # set the ansible_host variable to connect with the private IP address without changing the hostname
        ansible_host: private_ip_address
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0

  - name: EC2 Dynamic Source - RHEL7 Development - ALL
    inventory: ALL Development
    source: ec2
    source_vars:
      regions:
        - "{{ workshop_ec2_region }}"
      filters:
        tag:ContentView: RHEL7
        tag:Environment: Dev
        tag:Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
        tag:guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
      hostnames:
        - tag:NodeName
      keyed_groups:
        - prefix: cv
          key: tags['ContentView']
        - prefix: env
          key: tags['ContentView'] ~ '_' ~ tags['Environment']
        - prefix: os
          key: tags['foreman_operatingsystem_name']
        - prefix: AnsibleGroup
          key: tags['AnsibleGroup']
      compose:
        # set the ansible_host variable to connect with the private IP address without changing the hostname
        ansible_host: private_ip_address
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0

  - name: EC2 Dynamic Source - RHEL7 Production
    inventory: RHEL7 Production
    source: ec2
    source_vars:
      regions:
        - "{{ workshop_ec2_region }}"
      filters:
        tag:ContentView: RHEL7
        tag:Environment: Prod
        tag:Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
        tag:guid: "{{ lookup('env', 'AWX_HOST' ).split('.')[1] }}"
      hostnames:
        - tag:NodeName
        - tag:Name
        - private-dns-name
      keyed_groups:
        - prefix: cv
          key: tags['ContentView']
        - prefix: env
          key: tags['ContentView'] ~ '_' ~ tags['Environment']
        - prefix: os
          key: tags['foreman_operatingsystem_name']
        - prefix: AnsibleGroup
          key: tags['AnsibleGroup']
      compose:
        # set the ansible_host variable to connect with the private IP address without changing the hostname
        ansible_host: private_ip_address
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0

  - name: inventory_centos7_dev.aws_ec2
    inventory: EXAMPLE dynamic project inventory
    source: scm
    source_project: Automated Management
    source_path: inventory/inventory_centos7_dev.aws_ec2.yml
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0

  - name: inventory_rhel7_dev.aws_ec2
    inventory: EXAMPLE dynamic project inventory
    source: scm
    source_project: Automated Management
    source_path: inventory/inventory_rhel7_dev.aws_ec2.yml
    overwrite: true
    update_on_launch: false
    update_cache_timeout: 0
