---
tower_projects:
  - name: Fact Scan
    organization: Default
    scm_type: git
    scm_url: 'https://github.com/ansible/awx-facts-playbooks.git'

  - name: Three Tier App / Dev
    organization: Default
    scm_type: git
    scm_url: 'https://github.com/heatmiser/ansible-3tier-app.git'
    scm_branch: development
    scm_delete_on_update: true
    scm_update_on_launch: true
    scm_update_cache_timeout: 3600
