satellite_server_url: "{{ lookup('env', 'SATELLITE_SERVER_URL') }}"
satellite_username: "{{ lookup('env', 'SATELLITE_USERNAME') }}"
satellite_password: "{{ lookup('env', 'SATELLITE_PASSWORD') }}"
satellite_validate_certs: "{{ lookup('env', 'SATELLITE_VALIDATE_CERTS') | default(true) }}"
capsule_server: "{{ satellite_server_url }}"
capsule_port: '9090'
policy_name: 'all'
policy_scan: "{{ policy_name }}"
crontab_hour: 2
crontab_minute: 0
crontab_weekdays: 0
satellite_operations_scap_client_secure_logging: true
